<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\DrugFormulary;
use Carbon\Carbon;

class DrugFormularySeeder extends Seeder
{
    public function run()
    {
        $medicines = [
            [
                'name' => 'Amoxicillin',
                'generic_name' => 'Amoxicillin',
                'brand_name' => 'Amoxil',
                'atc_code' => 'J01CA04',
                'therapeutic_class' => 'Antibiotics',
                'strength' => '500mg',
                'form' => 'capsule',
                'formulation' => 'immediate-release',
                'dosage_form_details' => 'Hard gelatin capsules',
                'stock_quantity' => 150,
                'reorder_level' => 50,
                'unit_price' => 3315.00,
                'cost_price' => 2340.00,
                'manufacturer' => 'PharmaCorp',
                'batch_number' => 'AMX2024001',
                'expiry_date' => Carbon::now()->addMonths(18),
                'storage_conditions' => 'Store below 25°C, dry place',
                'status' => 'active',
                'requires_prescription' => true,
                'notes' => 'Broad-spectrum antibiotic for bacterial infections',
                'contraindications' => ['Penicillin allergy', 'Severe renal impairment'],
                'side_effects' => ['Nausea', 'Diarrhea', 'Skin rash', 'Abdominal pain'],
            ],
            [
                'name' => 'Paracetamol',
                'generic_name' => 'Acetaminophen',
                'brand_name' => 'Tylenol',
                'atc_code' => 'N02BE01',
                'therapeutic_class' => 'Analgesics',
                'strength' => '500mg',
                'form' => 'tablet',
                'formulation' => 'immediate-release',
                'dosage_form_details' => 'Film-coated tablets',
                'stock_quantity' => 300,
                'reorder_level' => 100,
                'unit_price' => 1560.00,
                'cost_price' => 1105.00,
                'manufacturer' => 'MediPharm',
                'batch_number' => 'PCM2024001',
                'expiry_date' => Carbon::now()->addMonths(24),
                'storage_conditions' => 'Store below 30°C',
                'status' => 'active',
                'requires_prescription' => false,
                'notes' => 'Pain reliever and fever reducer',
                'contraindications' => ['Severe liver disease', 'Alcohol dependency'],
                'side_effects' => ['Rare: liver damage with overdose', 'Skin rash'],
            ],
            [
                'name' => 'Metformin',
                'generic_name' => 'Metformin HCl',
                'brand_name' => 'Glucophage',
                'atc_code' => 'A10BA02',
                'therapeutic_class' => 'Antidiabetics',
                'strength' => '850mg',
                'form' => 'tablet',
                'formulation' => 'extended-release',
                'dosage_form_details' => 'Extended-release tablets',
                'stock_quantity' => 0,
                'reorder_level' => 25,
                'unit_price' => 5850.00,
                'cost_price' => 4160.00,
                'manufacturer' => 'DiabetCare',
                'batch_number' => 'MET2024001',
                'expiry_date' => Carbon::now()->addMonths(12),
                'storage_conditions' => 'Store at room temperature',
                'status' => 'active',
                'requires_prescription' => true,
                'notes' => 'First-line treatment for type 2 diabetes',
                'contraindications' => ['Renal impairment', 'Metabolic acidosis', 'Heart failure'],
                'side_effects' => ['Nausea', 'Diarrhea', 'Metallic taste', 'Vitamin B12 deficiency'],
            ],
            [
                'name' => 'Lisinopril',
                'generic_name' => 'Lisinopril',
                'brand_name' => 'Prinivil',
                'atc_code' => 'C09AA03',
                'therapeutic_class' => 'ACE Inhibitors',
                'strength' => '10mg',
                'form' => 'tablet',
                'formulation' => 'immediate-release',
                'dosage_form_details' => 'Scored tablets',
                'stock_quantity' => 80,
                'reorder_level' => 30,
                'unit_price' => 4647.50,
                'cost_price' => 3120.00,
                'manufacturer' => 'CardioMed',
                'batch_number' => 'LIS2024001',
                'expiry_date' => Carbon::now()->addMonths(15),
                'storage_conditions' => 'Store below 25°C',
                'status' => 'active',
                'requires_prescription' => true,
                'notes' => 'ACE inhibitor for hypertension and heart failure',
                'contraindications' => ['Pregnancy', 'Angioedema history', 'Bilateral renal artery stenosis'],
                'side_effects' => ['Dry cough', 'Hyperkalemia', 'Hypotension', 'Angioedema'],
            ],
            [
                'name' => 'Ibuprofen',
                'generic_name' => 'Ibuprofen',
                'brand_name' => 'Advil',
                'atc_code' => 'M01AE01',
                'therapeutic_class' => 'NSAIDs',
                'strength' => '400mg',
                'form' => 'tablet',
                'formulation' => 'immediate-release',
                'dosage_form_details' => 'Film-coated tablets',
                'stock_quantity' => 200,
                'reorder_level' => 75,
                'unit_price' => 2372.50,
                'cost_price' => 1625.00,
                'manufacturer' => 'PainRelief Inc',
                'batch_number' => 'IBU2024001',
                'expiry_date' => Carbon::now()->addMonths(20),
                'storage_conditions' => 'Store below 25°C',
                'status' => 'active',
                'requires_prescription' => false,
                'notes' => 'Non-steroidal anti-inflammatory drug (NSAID)',
                'contraindications' => ['Peptic ulcer', 'Severe heart failure', 'Third trimester pregnancy'],
                'side_effects' => ['GI upset', 'Headache', 'Dizziness', 'Fluid retention'],
            ],
            [
                'name' => 'Omeprazole',
                'generic_name' => 'Omeprazole',
                'brand_name' => 'Prilosec',
                'atc_code' => 'A02BC01',
                'therapeutic_class' => 'Proton Pump Inhibitors',
                'strength' => '20mg',
                'form' => 'capsule',
                'formulation' => 'delayed-release',
                'dosage_form_details' => 'Enteric-coated pellets in capsules',
                'stock_quantity' => 120,
                'reorder_level' => 40,
                'unit_price' => 3757.00,
                'cost_price' => 2535.00,
                'manufacturer' => 'GastroMed',
                'batch_number' => 'OME2024001',
                'expiry_date' => Carbon::now()->addMonths(16),
                'storage_conditions' => 'Store below 25°C, protect from moisture',
                'status' => 'active',
                'requires_prescription' => true,
                'notes' => 'Proton pump inhibitor for acid reflux and ulcers',
                'contraindications' => ['Hypersensitivity to benzimidazoles'],
                'side_effects' => ['Headache', 'Nausea', 'Diarrhea', 'Abdominal pain'],
            ],
            [
                'name' => 'Salbutamol Inhaler',
                'generic_name' => 'Salbutamol',
                'brand_name' => 'Ventolin',
                'atc_code' => 'R03AC02',
                'therapeutic_class' => 'Bronchodilators',
                'strength' => '100mcg/dose',
                'form' => 'inhaler',
                'formulation' => 'pressurized metered dose',
                'dosage_form_details' => 'Pressurized inhalation, suspension',
                'stock_quantity' => 45,
                'reorder_level' => 15,
                'unit_price' => 8450.00,
                'cost_price' => 5850.00,
                'manufacturer' => 'RespiCare',
                'batch_number' => 'SAL2024001',
                'expiry_date' => Carbon::now()->addMonths(14),
                'storage_conditions' => 'Store below 30°C, protect from frost',
                'status' => 'active',
                'requires_prescription' => true,
                'notes' => 'Bronchodilator for asthma and COPD',
                'contraindications' => ['Hypersensitivity to salbutamol'],
                'side_effects' => ['Tremor', 'Headache', 'Tachycardia', 'Muscle cramps'],
            ],
            [
                'name' => 'Cough Syrup',
                'generic_name' => 'Dextromethorphan',
                'brand_name' => 'Robitussin DM',
                'atc_code' => 'R05DA09',
                'therapeutic_class' => 'Antitussives',
                'strength' => '15mg/5ml',
                'form' => 'syrup',
                'formulation' => 'sugar-free',
                'dosage_form_details' => 'Oral solution, sugar-free',
                'stock_quantity' => 60,
                'reorder_level' => 20,
                'unit_price' => 2925.00,
                'cost_price' => 1950.00,
                'manufacturer' => 'CoughCare',
                'batch_number' => 'DXM2024001',
                'expiry_date' => Carbon::now()->addMonths(10),
                'storage_conditions' => 'Store below 25°C',
                'status' => 'active',
                'requires_prescription' => false,
                'notes' => 'Antitussive for dry cough',
                'contraindications' => ['MAOI use within 14 days', 'Chronic cough'],
                'side_effects' => ['Drowsiness', 'Dizziness', 'Nausea', 'Constipation'],
            ],
            [
                'name' => 'Hydrocortisone Cream',
                'generic_name' => 'Hydrocortisone',
                'brand_name' => 'Cortaid',
                'atc_code' => 'D07AA02',
                'therapeutic_class' => 'Topical Corticosteroids',
                'strength' => '1%',
                'form' => 'cream',
                'formulation' => 'topical',
                'dosage_form_details' => 'Topical cream, 30g tube',
                'stock_quantity' => 35,
                'reorder_level' => 10,
                'unit_price' => 2047.50,
                'cost_price' => 1365.00,
                'manufacturer' => 'DermaCare',
                'batch_number' => 'HYD2024001',
                'expiry_date' => Carbon::now()->addMonths(8),
                'storage_conditions' => 'Store below 25°C',
                'status' => 'active',
                'requires_prescription' => false,
                'notes' => 'Topical corticosteroid for skin inflammation',
                'contraindications' => ['Viral skin infections', 'Fungal infections'],
                'side_effects' => ['Skin atrophy', 'Burning sensation', 'Itching'],
            ],
            [
                'name' => 'Eye Drops',
                'generic_name' => 'Artificial Tears',
                'brand_name' => 'Refresh',
                'atc_code' => 'S01XA20',
                'therapeutic_class' => 'Ophthalmics',
                'strength' => '0.5%',
                'form' => 'drops',
                'formulation' => 'preservative-free',
                'dosage_form_details' => 'Sterile eye drops, single-use vials',
                'stock_quantity' => 25,
                'reorder_level' => 8,
                'unit_price' => 1592.50,
                'cost_price' => 1040.00,
                'manufacturer' => 'EyeCare',
                'batch_number' => 'EYE2024001',
                'expiry_date' => Carbon::now()->addMonths(6),
                'storage_conditions' => 'Store below 25°C, discard after opening',
                'status' => 'active',
                'requires_prescription' => false,
                'notes' => 'Lubricating eye drops for dry eyes',
                'contraindications' => ['Hypersensitivity to components'],
                'side_effects' => ['Temporary blurred vision', 'Eye irritation'],
            ],
            // Additional medicines for comprehensive testing
            [
                'name' => 'Aspirin',
                'generic_name' => 'Acetylsalicylic Acid',
                'brand_name' => 'Bayer',
                'atc_code' => 'N02BA01',
                'therapeutic_class' => 'Antiplatelet Agents',
                'strength' => '75mg',
                'form' => 'tablet',
                'formulation' => 'enteric-coated',
                'dosage_form_details' => 'Enteric-coated tablets',
                'stock_quantity' => 5,
                'reorder_level' => 20,
                'unit_price' => 1105.00,
                'cost_price' => 682.50,
                'manufacturer' => 'CardioMed',
                'batch_number' => 'ASP2024001',
                'expiry_date' => Carbon::now()->addDays(30),
                'storage_conditions' => 'Store below 25°C, dry place',
                'status' => 'active',
                'requires_prescription' => true,
                'notes' => 'Low-dose aspirin for cardiovascular protection',
                'contraindications' => ['Active bleeding', 'Severe liver disease', 'Children under 16'],
                'side_effects' => ['GI bleeding', 'Tinnitus', 'Allergic reactions'],
            ],
            [
                'name' => 'Insulin Glargine',
                'generic_name' => 'Insulin Glargine',
                'brand_name' => 'Lantus',
                'atc_code' => 'A10AE04',
                'therapeutic_class' => 'Long-acting Insulin',
                'strength' => '100 units/ml',
                'form' => 'injection',
                'formulation' => 'solution for injection',
                'dosage_form_details' => 'Pre-filled pen, 3ml',
                'stock_quantity' => 0,
                'reorder_level' => 5,
                'unit_price' => 16250.00,
                'cost_price' => 12350.00,
                'manufacturer' => 'DiabetCare',
                'batch_number' => 'INS2024001',
                'expiry_date' => Carbon::now()->addMonths(6),
                'storage_conditions' => 'Refrigerate 2-8°C, do not freeze',
                'status' => 'active',
                'requires_prescription' => true,
                'notes' => 'Long-acting insulin for diabetes management',
                'contraindications' => ['Hypoglycemia', 'Hypersensitivity to insulin glargine'],
                'side_effects' => ['Hypoglycemia', 'Injection site reactions', 'Weight gain'],
            ],
        ];

        foreach ($medicines as $medicineData) {
            DrugFormulary::updateOrCreate(
                ['name' => $medicineData['name'], 'strength' => $medicineData['strength']],
                $medicineData
            );
        }

        $this->command->info('Drug formulary sample data created successfully!');
    }
}