<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Patients Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            margin: 0;
            padding: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #0d9488;
            padding-bottom: 20px;
            background-color: #f0fdfa;
            padding: 20px;
            border-radius: 5px;
        }
        .header h1 {
            color: #0d9488;
            margin: 0;
            font-size: 24px;
            font-weight: bold;
        }
        .header .subtitle {
            color: #0d9488;
            font-size: 16px;
            font-weight: bold;
            margin: 5px 0;
        }
        .header p {
            margin: 5px 0;
            color: #666;
        }
        .summary {
            background-color: #f0fdfa;
            padding: 15px;
            border-radius: 5px;
            margin-bottom: 20px;
            border-left: 4px solid #0d9488;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #0d9488;
            color: white;
            font-weight: bold;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        tr:hover {
            background-color: #f0fdfa;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 10px;
            color: #666;
            border-top: 1px solid #ddd;
            padding-top: 10px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>MediCare HMS</h1>
        <p class="subtitle">Hospital Management System</p>
        <p>Patients Report</p>
        <p>Generated on {{ now()->format('F d, Y \a\t g:i A') }}</p>
    </div>

    <div class="summary">
        <strong>Summary:</strong> Total of {{ count($patients) }} patients in the system
    </div>

    <table>
        <thead>
            <tr>
                <th>Patient #</th>
                <th>Name</th>
                <th>Gender</th>
                <th>Age</th>
                <th>Phone</th>
                <th>Email</th>
                <th>Registered</th>
            </tr>
        </thead>
        <tbody>
            @foreach($patients as $patient)
            <tr>
                <td>{{ $patient['patient_number'] }}</td>
                <td>{{ $patient['name'] }}</td>
                <td>{{ $patient['gender'] }}</td>
                <td>{{ $patient['age'] }}</td>
                <td>{{ $patient['phone'] ?? '—' }}</td>
                <td>{{ $patient['email'] ?? '—' }}</td>
                <td>{{ $patient['registered'] }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>This report was generated by MediCare Hospital Management System</p>
        <p>© {{ date('Y') }} MediCare HMS. All rights reserved.</p>
    </div>
</body>
</html>