<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>HMS Scheduled Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 600px;
            margin: 0 auto;
            padding: 20px;
        }
        .header {
            background-color: #2563eb;
            color: white;
            padding: 20px;
            text-align: center;
            border-radius: 8px 8px 0 0;
        }
        .content {
            background-color: #f8f9fa;
            padding: 20px;
            border: 1px solid #dee2e6;
        }
        .footer {
            background-color: #6c757d;
            color: white;
            padding: 15px;
            text-align: center;
            border-radius: 0 0 8px 8px;
            font-size: 12px;
        }
        .report-details {
            background-color: white;
            padding: 15px;
            border-radius: 5px;
            margin: 15px 0;
        }
        .detail-row {
            display: flex;
            justify-content: space-between;
            margin-bottom: 10px;
            padding-bottom: 5px;
            border-bottom: 1px solid #eee;
        }
        .detail-label {
            font-weight: bold;
            color: #495057;
        }
        .attachment-info {
            background-color: #d4edda;
            border: 1px solid #c3e6cb;
            color: #155724;
            padding: 10px;
            border-radius: 5px;
            margin: 15px 0;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Hospital Management System</h1>
        <h2>Scheduled Report Delivery</h2>
    </div>

    <div class="content">
        <p>Hello,</p>
        
        <p>Your scheduled <strong>{{ $reportName }}</strong> report has been generated and is attached to this email.</p>

        <div class="report-details">
            <h3>Report Details</h3>
            
            <div class="detail-row">
                <span class="detail-label">Report Type:</span>
                <span>{{ $reportName }}</span>
            </div>
            
            <div class="detail-row">
                <span class="detail-label">Frequency:</span>
                <span>{{ ucfirst($reportConfig['frequency']) }}</span>
            </div>
            
            <div class="detail-row">
                <span class="detail-label">Format:</span>
                <span>{{ strtoupper($reportConfig['format']) }}</span>
            </div>
            
            <div class="detail-row">
                <span class="detail-label">Generated At:</span>
                <span>{{ $generatedAt }}</span>
            </div>
            
            @if(isset($reportConfig['department_id']))
            <div class="detail-row">
                <span class="detail-label">Department Filter:</span>
                <span>Applied</span>
            </div>
            @endif
            
            @if(isset($reportConfig['ward_id']))
            <div class="detail-row">
                <span class="detail-label">Ward Filter:</span>
                <span>Applied</span>
            </div>
            @endif
        </div>

        <div class="attachment-info">
            <strong>📎 Attachment:</strong> The report file is attached to this email. Please download and review the contents.
        </div>

        <p>This report was automatically generated by the Hospital Management System. If you have any questions or need assistance, please contact your system administrator.</p>

        <p>Best regards,<br>
        HMS Reporting System</p>
    </div>

    <div class="footer">
        <p>© {{ date('Y') }} Hospital Management System. All rights reserved.</p>
        <p>This is an automated message. Please do not reply to this email.</p>
    </div>
</body>
</html>